//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int ID { get; set; }
        public string TID { get; set; }
        public string FundingCode { get; set; }
        public string Fiscal { get; set; }
        public string month { get; set; }
        public string InvoiceNo { get; set; }
        public string Note { get; set; }
    }
}
